TimeFrame() now constructs 0x1 TimeFrame
xKDR/TSFrames.jl pull request #118
Opened 2022-11-09 12:17 UTC by harsharora21

This PR fixes issue #67

2022-11-10 06:49 UTC, chiraganand requested changes

2022-11-10 06:49 UTC, chiraganand commented on test/TimeFrame.jl
> +    @test eltype(index(tfi2))==Int
Can you include a test for `nrow() == 0` as well?

2022-11-10 20:04 UTC, harsharora21 commented on test/TimeFrame.jl
> +    @test eltype(index(tfi2))==Int
> Can you include a test for `nrow() == 0` as well?

Done

2022-11-11 05:17 UTC, chiraganand commented
@harsharora21 Can you change the constructor name based on changes in #119? Otherwise everything looks okay.

2022-11-11 05:18 UTC, chiraganand approved these changes

2022-11-12 10:37 UTC, merged