Add isregular
xKDR/TSFrames.jl pull request #130
Opened 2022-12-14 10:51 UTC by harsharora21

This PR added isregular function to TSFrames

2022-12-19 09:01 UTC, chiraganand requested changes

2022-12-19 09:01 UTC, chiraganand commented on src/utils.jl
> +    days = Day(timeperiod(timestamps[1],timestamps[2],Day(1)))
`TimeType` includes `Time`, `DateTime`, and `Date`. It would be better to write generic code for all of these types. Does providing `unit=typeof(timestamps)(1)` solve this for all types? If yes, then this default can be part of the method signature.

2022-12-19 12:37 UTC, harsharora21 commented on test/utils.jl
> +    @test isregular(dates_rep, Day(0)) == false
Done

2022-12-22 14:51 UTC, chiraganand commented on src/TSFrames.jl
> +    isregular
Exports are sorted alphabetically, please move `isregular` to it's rightful spot.

2022-12-22 19:00 UTC, harsharora21 commented on src/TSFrames.jl
> +    isregular
Fixed

2022-12-23 13:25 UTC, chiraganand commented on src/utils.jl
> +    if unit==:time
Can we call `:time` `:firstdiff` so that it is more clear

2022-12-28 09:07 UTC, chiraganand commented on src/TSFrames.jl
> +
Remove the extra line.

2023-01-05 16:39 UTC, harsharora21 commented on src/TSFrames.jl
> +
Fixed

2023-01-05 16:39 UTC, harsharora21 commented on src/utils.jl
> +    if unit==:time
Fixed

2023-01-05 16:40 UTC, harsharora21 commented on src/utils.jl
> +    days = Day(timeperiod(timestamps[1],timestamps[2],Day(1)))
Fixed

2023-01-06 06:22 UTC, chiraganand commented on src/utils.jl
> +isregular(timestamps::V, unit::T) where {V<:AbstractVector{TimeType}, T<:Dates.Period}
Can you put the `:firstdiff` default in the methods and add documentation for it also?

2023-01-11 15:51 UTC, harsharora21 commented on src/utils.jl
> +isregular(timestamps::V, unit::T) where {V<:AbstractVector{TimeType}, T<:Dates.Period}
Done

2023-02-10 07:46 UTC, chiraganand approved these changes

2023-02-10 07:49 UTC, chiraganand commented
@harsharora21 Why do we have `test_isregular()` and `test_regular_new()` in `test/utils.jl`? There should only be a single function for testing the `isregular()` function. Can you fix this quickly?

2023-02-10 09:56 UTC, harsharora21 commented
> @harsharora21 Why do we have `test_isregular()` and `test_regular_new()` in `test/utils.jl`? There should only be a single function for testing the `isregular()` function. Can you fix this quickly?

Fixed

2023-03-06 06:29 UTC, merged