Implement new `rollapply` method (for issue https://github.com/xKDR/TSFrames.jl/issues/49)
xKDR/TSFrames.jl pull request #131
Opened 2022-12-17 16:55 UTC by codetalker7

In this PR, we implement a new `rollapply` method. This method is inspired from [R's `zoo::rollapply`](https://www.rdocumentation.org/packages/zoo/versions/1.8-11/topics/rollapply); we now support a new keyword argument called `bycolumn`, which is `true` by default.

As an example, consider the following `TSFrame`.

```julia
using TSFrames, DataFrames, Statistics, StatsModels, StatsBase, GLM, Dates
df = DataFrame(Index=Date(2001, 1, 1):Day(1):Date(2001, 1, 10), inrchf=1:10, usdchf=1:10, eurchf=1:10, gbpchf=1:10, jpychf=1:10)
ts = TSFrame(df)
```

Now suppose, we want to apply the `Statistics.mean` method to each column in this `TSFrame`, with a window size of `5`. So, we do the following.

```julia
rollapply(Statistics.mean, ts, 5)
```

Now, suppose we want to do rolling regressions. For that, we write a custom `regress` function which operates on a `TSFrame`.

```julia
function regress(ts)
    ll = lm(@formula(inrchf ~ usdchf + eurchf + gbpchf + jpychf), ts.coredata[:, Not(:Index)])
    co = coef(ll)[coefnames(ll) .== "usdchf"]
    sd = Statistics.std(residuals(ll))
    return Dict("coeff" => co, "sd" => sd)
end
```
Now, we can do rolling regressions with `rollapply`.

```julia
rollapply(regress, ts, 5; bycolumn=false)
```

2022-12-19 09:48 UTC, chiraganand requested changes
For the implementation of `bycolumn=true` I think a simpler solution could be to use a supported DataFrames operation. For example: `combine(ts.coredata, Not(:Index) .=> median)`. Then vcat the results.

For the other case `bycolumn=false` why can't we apply `fun::Function` directly to the `TSFrame` object like: `res = fun(ts)` because it is known that `fun` takes a `TSFrame` type as input.

2022-12-19 09:48 UTC, chiraganand commented on src/rollapply.jl
> +        res = nothing
Better to declare `res` with the type it will hold so that compile is more informed. For example: `res::TSFrame = TSFrame()` or `res::Vector{TSFrame} = []`.

2022-12-19 09:48 UTC, chiraganand commented on src/rollapply.jl
> +    if bycolumn
See if you can include this if condition inside the `for` loop body below, the code will be more readable and easier to maintain. You can only put the differing code for both `bycolumn` values inside the `if ... else` blocks and rest of the code remains the same to avoid code duplication.

2022-12-26 15:23 UTC, codetalker7 commented on src/rollapply.jl
> +    if bycolumn
Hi @chiraganand I've tried to restructure the code to avoid duplication as much as possible. Also, instead of creating an empty `TSFrame`, now I'm just using the first window `TSFrame` as the starting point (and then just `vcat`ing everything else onto this). So we won't need the empty constructor here.

2022-12-28 09:06 UTC, chiraganand requested changes

2022-12-28 09:06 UTC, chiraganand commented on src/rollapply.jl
> +            res = vcat(res, [fun(currentWindow)])
It will be good to supply `cols=:orderequal` argument to both `DataFrames.vcat()` calls to avoid any unexpected results.

2022-12-28 09:06 UTC, chiraganand commented on src/rollapply.jl
> +function rollapply(fun::Function, ts::TSFrame, windowsize::Int; bycolumn=true)
Minor thing: can you change the order of columns to: `ts::TSFrame, fun::Function, windowsize, bycolumn` just to make it consistent with other TSFrames methods.

2022-12-28 12:43 UTC, codetalker7 commented on src/rollapply.jl
> +    res = bycolumn ? mapcols(col -> fun(col), DataFrame(firstWindow)[:, Not(:Index)]) : [fun(firstWindow)]
Made all these changes.

2022-12-28 12:44 UTC, codetalker7 commented on src/rollapply.jl
> +            res = vcat(res, [fun(currentWindow)])
Made this change. The second call to `vcat` is a `vcat` of `Vector`.

2022-12-28 12:45 UTC, codetalker7 commented on src/rollapply.jl
> +function rollapply(fun::Function, ts::TSFrame, windowsize::Int; bycolumn=true)
Done.

2022-12-28 13:03 UTC, codetalker7 commented
Hi @chiraganand. Should the old `rollapply` method be removed, or are we keeping it?

2022-12-28 14:21 UTC, codetalker7 commented
Hi @chiraganand. I've also written an error condition for `rollapply`, and I'm assuming that if `windowsize > TSFrames.nrow(ts)`, then we take `windowsize = TSFrames.nrow(ts)`. Added corresponding test cases as well.

2023-01-02 07:31 UTC, chiraganand commented
> Hi @chiraganand. Should the old `rollapply` method be removed, or are we keeping it?

I have removed it.

2023-01-02 07:32 UTC, chiraganand commented
> Hi @chiraganand. I've also written an error condition for `rollapply`, and I'm assuming that if `windowsize > TSFrames.nrow(ts)`, then we take `windowsize = TSFrames.nrow(ts)`. Added corresponding test cases as well.

Yes, this is good.

2023-01-02 07:37 UTC, chiraganand approved these changes

2023-01-02 07:53 UTC, merged