New constructors for empty `TSFrame`s.
xKDR/TSFrames.jl pull request #133
Opened 2022-12-22 13:32 UTC by codetalker7

This PR addresses issue https://github.com/xKDR/TSFrames.jl/issues/132. A new constructor has been added, which takes in the type of `Index` and the names and types of the columns of the resultant `TSFrame`, and creates an empty `TSFrame` object. Corresponding documentation and tests have been added as well.

2022-12-22 14:50 UTC, chiraganand requested changes

2022-12-22 14:50 UTC, chiraganand commented on src/TSFrame.jl
> +TSFrame(T::DataType; n::Int=1)
I suggest changing variable name `T` to `IndexType` so that it is clear to the user what the first argument is.

2022-12-22 15:15 UTC, codetalker7 commented on src/TSFrame.jl
> +TSFrame(T::DataType; n::Int=1)
Done.

2022-12-28 08:50 UTC, chiraganand approved these changes

2022-12-28 08:51 UTC, merged